version: '3'

services:
  app:
    build: .
    container_name: danflix-video-encoder-app
    volumes:
    - .:/go/src/

  rabbit:
    image: rabbitmq:3.9.13-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
